<a href="https://colab.research.google.com/github/gafurjanoff/Data_Science_/blob/main/conditional_operators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr


In [ ]:
cond = np.array([True, False, True, True, False])


In [ ]:
result = np.where(cond , xarr , yarr)

In [ ]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arr = np.random.randn(4,4)
arr

array([[ 0.30301787,  0.12444017,  0.52516392,  0.73620376],
       [-0.35521256, -0.39553969, -0.45756556,  0.23409624],
       [ 0.47593794, -0.68648995, -0.85098652,  0.02956985],
       [-1.0685194 ,  2.05538417,  0.30417932, -0.37008438]])

In [ ]:
results = np.where(arr<0 , -2 , 2)

In [ ]:
results

array([[ 2,  2,  2,  2],
       [-2, -2, -2,  2],
       [ 2, -2, -2,  2],
       [-2,  2,  2, -2]])

In [ ]:
remainder,  integer = np.modf(arr)

In [ ]:
remainder


array([[ 0.30301787,  0.12444017,  0.52516392,  0.73620376],
       [-0.35521256, -0.39553969, -0.45756556,  0.23409624],
       [ 0.47593794, -0.68648995, -0.85098652,  0.02956985],
       [-0.0685194 ,  0.05538417,  0.30417932, -0.37008438]])

# where Function

- np.where(condition, X-axis , Y-axis)




In [ ]:
integer

array([[ 0.,  0.,  0.,  0.],
       [-0., -0., -0.,  0.],
       [ 0., -0., -0.,  0.],
       [-1.,  2.,  0., -0.]])

# Arithmatic operations

- add
- subtract
- sqrt
- divide
- mulptiply



In [ ]:
arr1 = np.arange(10).reshape(5,2)

In [ ]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr2 = np.arange(5,15).reshape(5,2)

In [ ]:
arr2

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [ ]:
arr1*arr2

array([[  0,   6],
       [ 14,  24],
       [ 36,  50],
       [ 66,  84],
       [104, 126]])

In [ ]:
arr1/arr2

array([[0.        , 0.16666667],
       [0.28571429, 0.375     ],
       [0.44444444, 0.5       ],
       [0.54545455, 0.58333333],
       [0.61538462, 0.64285714]])

In [ ]:
arr1+arr2

array([[ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23]])

In [ ]:
arr1-arr2

array([[-5, -5],
       [-5, -5],
       [-5, -5],
       [-5, -5],
       [-5, -5]])

In [ ]:
arr1**2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [ ]:
arr2**2

array([[ 25,  36],
       [ 49,  64],
       [ 81, 100],
       [121, 144],
       [169, 196]])

In [ ]:
arr2**0.5

array([[2.23606798, 2.44948974],
       [2.64575131, 2.82842712],
       [3.        , 3.16227766],
       [3.31662479, 3.46410162],
       [3.60555128, 3.74165739]])