<a href="https://colab.research.google.com/github/gafurjanoff/Data_Science_/blob/main/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra

In [2]:
import numpy as np

In [5]:
arr1 = np.arange(1,7).reshape(2,3)

In [17]:
arr2 = np.arange(1,11).reshape(5,2)

In [18]:
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
arr2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
np.add(arr1,arr2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [21]:
arr1+arr2

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [22]:
arr1*arr2

array([[  1,   4],
       [  9,  16],
       [ 25,  36],
       [ 49,  64],
       [ 81, 100]])

In [23]:
arr1*5

array([[ 5, 10],
       [15, 20],
       [25, 30],
       [35, 40],
       [45, 50]])

In [24]:
arr2*5

array([[ 5, 10],
       [15, 20],
       [25, 30],
       [35, 40],
       [45, 50]])

In [26]:
arr1 - arr2

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [29]:
arr_new = np.arange(6).reshape(2,3)
arr_new2 = np.arange(6).reshape(3,2)

In [30]:
arr_new.dot(arr_new2)

array([[10, 13],
       [28, 40]])

In [32]:
np.dot(arr_new, arr_new2)

array([[10, 13],
       [28, 40]])

# Linear Agebra built in library

There are different types of objects (or structures) in linear algebra:

- Scalar: Single number
- Vector: Array of numbers
- Matrix: 2-dimensional array of numbers
- Tensor: N-dimensional array of numbers where n > 2

In [35]:
np.matmul(arr_new , arr_new2)

array([[10, 13],
       [28, 40]])

In [38]:
arr = np.array([0, 1, 2, 3])

In [39]:
arr.cumsum()

array([0, 1, 3, 6])