<a href="https://colab.research.google.com/github/gafurjanoff/Data_Science_/blob/main/sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sorting

In [2]:
import numpy as np

In [3]:
arr = np.random.randn(10)

In [4]:
arr

array([-1.30463895,  2.13037022, -0.55382164,  1.77065824, -0.72436049,
        1.90635779,  0.5853978 , -0.05229487, -0.00365267, -0.04166345])

In [5]:
sorted_arr = np.sort(arr)

In [6]:
sorted_arr

array([-1.30463895, -0.72436049, -0.55382164, -0.05229487, -0.04166345,
       -0.00365267,  0.5853978 ,  1.77065824,  1.90635779,  2.13037022])

In [7]:
arr.sort()
arr

array([-1.30463895, -0.72436049, -0.55382164, -0.05229487, -0.04166345,
       -0.00365267,  0.5853978 ,  1.77065824,  1.90635779,  2.13037022])

In [17]:
rev_arr = -np.sort(arr)
rev_arr

array([ 1.30463895,  0.72436049,  0.55382164,  0.05229487,  0.04166345,
        0.00365267, -0.5853978 , -1.77065824, -1.90635779, -2.13037022])

In [18]:
rev_arr = -np.sort(-arr)
rev_arr

array([ 2.13037022,  1.90635779,  1.77065824,  0.5853978 , -0.00365267,
       -0.04166345, -0.05229487, -0.55382164, -0.72436049, -1.30463895])

# Sorting in 2 Dimensional Arrays


In [23]:
new_arr = np.random.randn(2,4)

In [25]:
new_arr

array([[-0.14811154,  0.17021884, -1.13306813,  1.42604848],
       [-1.0483174 ,  0.54334381,  1.10418693,  0.4175413 ]])

In [28]:
row_sort = np.sort(new_arr, axis=0)
row_sort

array([[-1.0483174 ,  0.17021884, -1.13306813,  0.4175413 ],
       [-0.14811154,  0.54334381,  1.10418693,  1.42604848]])

In [29]:
clmn_sort = np.sort(new_arr, axis=1)
clmn_sort

array([[-1.13306813, -0.14811154,  0.17021884,  1.42604848],
       [-1.0483174 ,  0.4175413 ,  0.54334381,  1.10418693]])