<a href="https://colab.research.google.com/github/gafurjanoff/Data_Science_/blob/main/tasks_of_mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np

np.version

np.show_config

<function numpy.__config__.show()>

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
ls = [1,2,3,4,5,6,7,8,9,0]

arr = np.array(ls)

arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
arr_zero = np.zeros((9,9))
arr_zero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
arr = np.arange(20).reshape(5,4)

print(np.size(arr))

arr.itemsize

20


8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(np.add(2,3))

Signed integer type, compatible with Python `int` and C ``long``.

:Character code: ``'l'``
:Canonical name: `numpy.int_`
:Alias on this platform (Linux x86_64): `numpy.int64`: 64-bit signed integer (``-9_223_372_036_854_775_808`` to ``9_223_372_036_854_775_807``).
:Alias on this platform (Linux x86_64): `numpy.intp`: Signed integer large enough to fit pointer, compatible with C ``intptr_t``.


#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
arr =  np.arange(12).reshape(3,4)

arr[1,1] = 1

arr

array([[ 0,  1,  2,  3],
       [ 4,  1,  6,  7],
       [ 8,  9, 10, 11]])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
arr = np.arange(20,60)

arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])


#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
arr = np.arange(20,50)

arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr = np.arange(12,21).reshape(3,3)

arr

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
ls = [3, 7,  0,0, 9, 0]
arr = np.array(ls)

for i , value in enumerate(arr):
  if value != 0:
     print(i)

0
1
4


#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
d3_array = np.random.randn(2,2,2)

d3_array

array([[[-0.53011063, -0.2853134 ],
        [ 0.53842011,  1.32756574]],

       [[ 0.47051327,  0.29054555],
        [-3.52657826,  0.18604789]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
arr = np.random.randn(9,9)

print(np.max(arr))
print(np.min(arr))

1.9867539959127367
-2.9634777882175873


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
arr = np.random.randn(6,3)
arr2 = np.random.randn(3,4)

product = np.dot(arr,arr2)

product

array([[ 0.42342146, -0.802604  , -0.95979091, -0.25794743],
       [ 0.02371454,  1.43628303,  0.07101918,  1.44549813],
       [ 4.00755275,  0.26491377,  0.73152968,  4.37110326],
       [ 0.30128541,  1.54266266,  0.39695198,  1.80763076],
       [-0.38635466, -0.86630562,  0.16124255, -1.2810215 ],
       [ 0.65513775, -1.17788191,  0.50983498, -0.53948266]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a = np.array([1, 2])
b = np.array([4, 5])


print("Array a:", a)
print("Array b:", b)

print("a > b")
print(a > b)

print("a >= b")
print(a >= b)

print("a < b")
print(a < b)

print("a <= b")
print(a <= b)

Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-64-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-64-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-64-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
ls = list(range(10))

arr = np.array(ls)

ls2 = list(range(20))

arr_new = np.array(ls2)

np.intersect1d(arr,arr_new)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
arr_rand = np.random.randn(10)
print(arr_rand)
remainder, integer = np.modf(arr_rand)
print(integer)
for i in integer:
  if i > 0:
    print(i)

# nums = np.where(integer > 0)
# solid_number  = arr[nums]
# solid_number

[-0.31642934  0.78182313  0.24959669 -1.12523712  1.61882239  1.99728828
  0.92151745  1.36145795 -0.41588348 -0.66635066]
[-0.  0.  0. -1.  1.  1.  0.  1. -0. -0.]
1.0
1.0
1.0


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
array = np.arange(0, 2, 2/9)
three_array = array.reshape(3, 3)

print(three_array)

[[0.         0.22222222 0.44444444]
 [0.66666667 0.88888889 1.11111111]
 [1.33333333 1.55555556 1.77777778]]


#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
matr = np.random.rand(10)
matr

np.sort(matr)

array([0.17752048, 0.30531172, 0.38477409, 0.67808011, 0.69421392,
       0.70302351, 0.737537  , 0.78382151, 0.82025524, 0.93657319])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [ ]:
matr = np.random.rand(10)
matr2 = np.random.rand(20)

np.array_equal(matr,matr2)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
erre = np.arange(18).reshape(6,3)

erre2 = np.arange(12).reshape(3,4)

np.dot(erre,erre2)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218],
       [164, 203, 242, 281],
       [200, 248, 296, 344]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [ ]:
arr = np.random.randn(5)
max_element = np.max(arr)
max_index = np.where(arr == max_element)
arr[max_index] = 0

arr



array([-0.30286566, -0.08438234,  0.39981232,  0.        ,  0.31958343])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
# from datetime import datetime, timedelta
# today = datetime.now().date()
# yesterday = today - timedelta(days=1)
# tomorrow = today + timedelta(days=1)
# print("Today's date:", today)
# print("Yesterday's date:", yesterday)
# print("Tomorrow's date:", tomorrow)
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print("Today's date:", today)
print("Yesterday's date:", yesterday)
print("Tomorrow's date:", tomorrow)

Today's date: 2024-04-03
Yesterday's date: 2024-04-02
Tomorrow's date: 2024-04-04


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
start_date = np.datetime64('2016-01-01')
end_date = np.datetime64('2016-02-01')

dates_jan_2016 = np.arange(start_date, end_date, dtype='datetime64[D]')

for date in dates_jan_2016:
    print(date)

2016-01-01
2016-01-02
2016-01-03
2016-01-04
2016-01-05
2016-01-06
2016-01-07
2016-01-08
2016-01-09
2016-01-10
2016-01-11
2016-01-12
2016-01-13
2016-01-14
2016-01-15
2016-01-16
2016-01-17
2016-01-18
2016-01-19
2016-01-20
2016-01-21
2016-01-22
2016-01-23
2016-01-24
2016-01-25
2016-01-26
2016-01-27
2016-01-28
2016-01-29
2016-01-30
2016-01-31


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
eray = np.random.randn(10)

integer_part1 = array % 1

integer_part2 = np.floor(array)

integer_arr3 = array.astype(int)

integer_part4 = np.trunc(array)

print(integer_part1)
print(integer_part2)
print(integer_arr3)
print(integer_part4)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 0.11111111
 0.33333333 0.55555556 0.77777778]
[0. 0. 0. 0. 0. 1. 1. 1. 1.]
[0 0 0 0 0 1 1 1 1]
[0. 0. 0. 0. 0. 1. 1. 1. 1.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [ ]:
arr = np.random.randn(15)
arr2 = np.random.randn(10)
summ1 = np.add.reduce(arr)

summ2 = np.add.reduce(arr2)

print(summ1)
print(summ2)

6.804536426157002
-1.9598678695258778


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:

vektr = np.array([[1, 2, 3, 4, 5]])

new_arry = np.insert(vektr, 1, [0,0,0])
new_arry2 = np.insert(new_arry, 5, [0,0,0])
new_arry3 = np.insert(new_arry2, 9, [0,0,0])
new_arry4 = np.insert(new_arry3, 13, [0,0,0])
new_arry5 = np.insert(new_arry4, 17, [0,0,0])

print(new_arry5)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [7]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
results = []

for i in range(len(a) - 3):
    result = a[i:i+4]
    results.append(result)

print(results)

[[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 12], [10, 11, 12, 13], [11, 12, 13, 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [1]:
def find_similar_elements(arr):
    similar_elements = list()
    for i in range(len(arr)):
        for j in range(i+1, len(arr)):
            if arr[i] == arr[j] and arr[i] not in similar_elements:
                similar_elements.append(arr[i])
    return similar_elements

arr = [1, 2, 3, 4, 2, 5, 6, 7, 3, 8, 9, 5]
similar = find_similar_elements(arr)
print("Similar elements:", similar)


Similar elements: [2, 3, 5]


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`